# Allowed lists for UI and seeding/pruning
ALLOWED_ROLES = ("RIDER", "STRAPPER", "MEDIA", "TREADMILL", "WATERWALKERS", "FARRIER", "VET")
ALLOWED_LOCS  = ("FARM", "FLEMINGTON", "PAKENHAM")

ROLE_WHERE = "code IN ('RIDER','STRAPPER','MEDIA','TREADMILL','WATERWALKERS','FARRIER','VET')"
LOC_WHERE  = "code IN ('FARM','FLEMINGTON','PAKENHAM')"
